### ISSUE TITLE
Reorganize Components

### ISSUE THREAD

**Issue by HariSeldon23** [KudooCloud/kudoo-shared-components#3]
I'd like us to add a bit more structure to our components. I see a hierarchial structure being the best bet which will allow us to more easily organize our growing list of Components.

The tree should be:
* Bosons
* Nuclei
* Atoms

Bosons are the base components. They will be the smallest components. Things such as buttons, checkboxes all fit into this category.

Nuclei contain Components made up of a few Boson components.

Atoms are the building blocks for our application. They will include the Drawer, Screens and big components that make up the application.

So I'd like us to start moving into this structure as per the below:

# bosons
* Button
* Checkbox
* CircularProgressBar (This should be renamed to Progress Bar and Circular should be a prop)
* CompanyCard (This should be renamed Card)
* ProjectCard (Can we not merge this and CompanyCard together?)
* SubscriptionCard (We shouldn't have three different Card components, we should consolidate them)
* DatePicker
* DottedCreateButton
* Dropdown
* FieldLabel
* FileBlock
* LinearProgressBar (This should be merged with CircularProgressBar and then users can choose whether they'd like to use Circular or Linear)
* Logo
* Map
* Pagination
* RadioButton
* SearchInput
* Table
* TermsOfService
* TextField
* ToggleButton
* ToggleSwitch
* TriangleArrow
* WizardSteps

# nuclei
* AddressForm
* AlertDialog
* Modal (Can we not merge Modal with AlertDialog? What's the difference?)
* Attachment (This needs to be the same as for Timesheets)
* ContactForm
* CustomerForm
* EmailInputFields
* HeaderNavMenu
* Jumbotron
* Newsletter (This will also need to be added to Storybook)
* PhoneNumberField
* SectionHeader
* Signature
* TimesheetRowDisplay
* WeekPeriod

# atoms
* Drawer
* Footer
* Tabs
* HeaderBar

# HOC??
* ErrorBoundary
* I18nLoader
* Loading
* NotFound

#  further discussion
* Animation?
* Header - we already have HeaderBar. Are we using Header?
* SocialLoginButton - Are we using this at all?

**Comment by SarjuHansaliya** [comment]
@HariSeldon23 

- Animation will be Removed, we are not using
- Header will be Removed, we are not using
- HeaderNavMenu will be Removed, we are not using
- SocialLoginButton will be moved to Atoms, Currently we are not using it but it is made for google and facebook sign in so we might need it in future
- NotFound will be moved to Atoms
- Loading will be moved to Bosons as it is base component for loading

- CompanyCard, ProjectCard, SubscriptionCard , these are 3 different component with 3 different designs. So I am not sure how to consolidate them into one unless we want to keep 3 different design in one big component.

- CircularProgressBar and LinearProgressBar can be merged, I will check on it

- AlertDialog is sub version of Modal specifically for only showing confirmation modal. But yes we can remove AlertDialog as Modal is capable of handling what AlertDialog does now.

- I think Modal should be in bosons as it is Base Component.

**Comment by HariSeldon23** [comment]
Happy with all this. Let's leave the *Cards separate then. Pointless having bloated components. 

Marking this as closed
